### ISSUE TITLE
Loading Environment from MMC... *** Warning - bad CRC,

### ISSUE THREAD

**Issue by wangbo13** [bootlin/openwrt-feed-st#1]
I've tried replacing multiple TF cards, but the startup still prompts this error

**Comment by thom24** [comment]
Having this message during the first boot is not an issue.

During the first boot, the u-boot-env partition (where env variables are stored) is empty.
That's why you get this error. So U-Boot uses its default environment (stored in the U-Boot image) for the first boot.
Then it writes its environment to the SDCard (in u-boot-env partition).

In next boots, U-Boot will successfully loads its environment from the SDCard, so you will not have this message anymore.

Note that u-boot-env partition is preserved during system upgrade (even if "keep settings" is not set).
